version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "3000:3000"

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]